Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/3c31c8cb4eb3eaed4de1a1438fa4f83e550fa51e/test/jdk/java/lang/invoke/MethodHandlesGeneralTest.java#L1 is failing consistantly for JDK11-openj9 (hotspot unaffected)
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows,  openjdk_x86-64_mac
```
12:09:31  openjdk version "11.0.5" 2019-10-15
12:09:31  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+6-201909092135)
12:09:31  Eclipse OpenJ9 VM AdoptOpenJDK (build master-dc4bacd49, JRE 11 Linux amd64-64-Bit Compressed References 20190909_330 (JIT enabled, AOT enabled)
12:09:31  OpenJ9   - dc4bacd49
12:09:31  OMR      - 7e9584ea
12:09:31  JCL      - 3c31c8cb4e based on jdk-11.0.5+6)
```

Optional info
-------------

- intermittent failure (no): 
- new test:  
- Possibly related to #6802, #6868 and #6800 due to the use of MethodHandles (unique to hotspot?)

Failure output (captured from console output)
---------------------------------------------
```
12:12:03  STDOUT:
12:12:03  STDERR:
12:12:03  JavaTest Message: JUnit Failure: testFindVirtualClone(test.java.lang.invoke.MethodHandlesGeneralTest): negative test erroneously passed expected:<false> but was:<true>
12:12:03  java.lang.AssertionError: negative test erroneously passed expected:<false> but was:<true>
12:12:03  	at org.junit.Assert.fail(Assert.java:93)
12:12:03  	at org.junit.Assert.failNotEquals(Assert.java:647)
12:12:03  	at org.junit.Assert.assertEquals(Assert.java:128)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindVirtual(MethodHandlesGeneralTest.java:240)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindVirtual(MethodHandlesGeneralTest.java:215)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindVirtualClone0(MethodHandlesGeneralTest.java:187)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest$$Lambda$15.00000000380FE7D0.run(Unknown Source)
12:12:03  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor$$Lambda$10.00000000380D8E50.run(Unknown Source)
12:12:03  	at jdk.testlibrary.Utils.filterException(Utils.java:285)
12:12:03  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindVirtualClone(MethodHandlesGeneralTest.java:181)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
12:12:03  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
12:12:03  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
12:12:03  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
12:12:03  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
12:12:03  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
12:12:03  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
12:12:03  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
12:12:03  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
12:12:03  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
12:12:03  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
12:12:03  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
12:12:03  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
12:12:03  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
12:12:03  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
12:12:03  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
12:12:03  	at org.junit.runners.Suite.runChild(Suite.java:128)
12:12:03  	at org.junit.runners.Suite.runChild(Suite.java:24)
12:12:03  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
12:12:03  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
12:12:03  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
12:12:03  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
12:12:03  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
12:12:03  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
12:12:03  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:12:03  	at java.base/java.lang.Thread.run(Thread.java:831)
12:12:03  
12:12:03  JavaTest Message: JUnit Failure: testFindSpecial(test.java.lang.invoke.MethodHandlesGeneralTest): negative test erroneously passed expected:<false> but was:<true>
12:12:03  java.lang.AssertionError: negative test erroneously passed expected:<false> but was:<true>
12:12:03  	at org.junit.Assert.fail(Assert.java:93)
12:12:03  	at org.junit.Assert.failNotEquals(Assert.java:647)
12:12:03  	at org.junit.Assert.assertEquals(Assert.java:128)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindSpecial(MethodHandlesGeneralTest.java:346)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindSpecial(MethodHandlesGeneralTest.java:312)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindSpecial0(MethodHandlesGeneralTest.java:287)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest$$Lambda$16.00000000380FEBA0.run(Unknown Source)
12:12:03  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor$$Lambda$10.00000000380D8E50.run(Unknown Source)
12:12:03  	at jdk.testlibrary.Utils.filterException(Utils.java:285)
12:12:03  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFindSpecial(MethodHandlesGeneralTest.java:278)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
12:12:03  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
12:12:03  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
12:12:03  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
12:12:03  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
12:12:03  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
12:12:03  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
12:12:03  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
12:12:03  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
12:12:03  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
12:12:03  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
12:12:03  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
12:12:03  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
12:12:03  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
12:12:03  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
12:12:03  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
12:12:03  	at org.junit.runners.Suite.runChild(Suite.java:128)
12:12:03  	at org.junit.runners.Suite.runChild(Suite.java:24)
12:12:03  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
12:12:03  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
12:12:03  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
12:12:03  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
12:12:03  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
12:12:03  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
12:12:03  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:12:03  	at java.base/java.lang.Thread.run(Thread.java:831)
12:12:03  
12:12:03  JavaTest Message: JUnit Failure: testFoldArguments(test.java.lang.invoke.MethodHandlesGeneralTest): The value of the fold position: 1 must be in a range from 0 to 1
12:12:03  java.lang.IllegalArgumentException: The value of the fold position: 1 must be in a range from 0 to 1
12:12:03  	at java.base/java.lang.invoke.MethodHandles.foldArgumentsCommon(MethodHandles.java:2656)
12:12:03  	at java.base/java.lang.invoke.MethodHandles.foldArguments(MethodHandles.java:2611)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFoldOrCollectArguments(MethodHandlesGeneralTest.java:1346)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFoldOrCollectArguments(MethodHandlesGeneralTest.java:1286)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFoldArguments1(MethodHandlesGeneralTest.java:1267)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest$$Lambda$36.000000003813CF10.run(Unknown Source)
12:12:03  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor$$Lambda$10.00000000380D8E50.run(Unknown Source)
12:12:03  	at jdk.testlibrary.Utils.filterException(Utils.java:285)
12:12:03  	at test.java.lang.invoke.lib.CodeCacheOverflowProcessor.runMHTest(CodeCacheOverflowProcessor.java:71)
12:12:03  	at test.java.lang.invoke.MethodHandlesGeneralTest.testFoldArguments(MethodHandlesGeneralTest.java:1255)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
12:12:03  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
12:12:03  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
12:12:03  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
12:12:03  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
12:12:03  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
12:12:03  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
12:12:03  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
12:12:03  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
12:12:03  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
12:12:03  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
12:12:03  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
12:12:03  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
12:12:03  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
12:12:03  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
12:12:03  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
12:12:03  	at org.junit.runners.Suite.runChild(Suite.java:128)
12:12:03  	at org.junit.runners.Suite.runChild(Suite.java:24)
12:12:03  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
12:12:03  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
12:12:03  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
12:12:03  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
12:12:03  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
12:12:03  	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
12:12:03  	at org.junit.runner.JUnitCore.run(JUnitCore.java:127)
12:12:03  	at org.junit.runner.JUnitCore.runClasses(JUnitCore.java:76)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:76)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:12:03  	at java.base/java.lang.Thread.run(Thread.java:831)
12:12:03  
12:12:03  java.lang.Exception: JUnit test failure
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:92)
12:12:03  	at com.sun.javatest.regtest.agent.JUnitRunner.main(JUnitRunner.java:43)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:12:03  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:12:03  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:03  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:03  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
12:12:03  	at java.base/java.lang.Thread.run(Thread.java:831)
12:12:03  
12:12:03  JavaTest Message: Test threw exception: java.lang.Exception: JUnit test failure
12:12:03  JavaTest Message: shutting down test
```
